### ISSUE TITLE
NPM Package is down!

### ISSUE THREAD

**Issue by aleixfargas** [kainonly/cordova-support-kotlin#10]
Hello, the npm package is not available at this moment. 
Please can someone fix it? We're not able to compile our project anymore!

https://www.npmjs.com/package/cordova-support-kotlin
![Screenshot 2021-11-08 at 10 59 43](https://user-images.githubusercontent.com/14315473/140721991-0356c96b-9455-45d4-899f-8491ebe55794.png)

**Comment by kainonly** [comment]
Sorry, this is a mistake in my operation, it will be republished shortly after the freeze is over

**Comment by kainonly** [comment]
hi, i have  republish, is it normal now?

**Comment by aleixfargas** [comment]
Thank you @kainonly Now i can see the package, but our dependency is the 1.2.1 version. You have uploaded only the v1.2.2. Can you upload the 1.2.1 too please? Thank you very much. I really appreciate your efforts.

**Comment by aleixfargas** [comment]
Or it is safe to use v1.2.2? What changes does it include comparing with v1.2.1?

**Comment by kainonly** [comment]
Can only revoke 1.2.2 and then release 1.2.1，cannot be republished until 24 hours have passed.

**Comment by aleixfargas** [comment]
No problem I will try to point to 1.2.2 then. Thanks 😉

**Comment by aleixfargas** [comment]
I see that you have revoked 1.2.2 finally. Please, advise us when 1.2.1 is finally published. When it will be available again I will close the issue. Thanks again.

**Comment by kainonly** [comment]
hi, the 1.2.1 is finally published.

**Comment by aleixfargas** [comment]
Now is working! Thank you @kainonly .
For those who has the same issue, in the last build, I had to do:
`cordova plugin rm cordova-support-kotlin`
`cordova plugin add cordova-support-kotlin --save`

To fix the packages.json integrity error:
![Screenshot 2021-11-09 at 18 17 33](https://user-images.githubusercontent.com/14315473/140973192-96206960-fe7e-4526-9ced-745eb19c47b4.png)
